# Generated by Django 2.1 on 2021-04-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('description', models.TextField(default='')),
                ('count', models.FloatField(default=0)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
    ]
